[package]
name = "clap_for_s3"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-credential-types = { workspace = true }
aws-sdk-s3 = { workspace = true }
clap = { workspace = true }
url = { workspace = true }
