repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
        exclude: ^charts\/.*\/templates\/.*\.yaml
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        entry: cargo fmt
        args:
          - --manifest-path=backend/Cargo.toml
          - --check
          - --all
          - --
        language: system
        files: \.rs$
      - id: cargo-check
        name: cargo check
        entry: cargo check
        args:
          - --manifest-path=backend/Cargo.toml
        language: system
        files: \.rs$
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy
        args:
          - --manifest-path=backend/Cargo.toml
          - --
          - -Dwarnings
        language: system
        files: \.rs$
        pass_filenames: false
