apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: XChemLab
  title: xchemlab
  description: A collection of services which comprise the XChemLab deployment 
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: DiamondLightSource/xchemlab
  tags:
    - Rust
spec:
  type: application
  lifecycle: production
  owner: group:data-analysis