[package]
name = "backend"
version = "0.1.0"
edition = "2021"
authors = ["Garry O'Donnell <garry.o'donnell@diamond.ac.uk>"]
description = "An XChemLab service, used to export legacy SoakDB sqlite files."
license = "Apache-2.0"
repository = "https://github.com/garryod/xchemlab_soakdb_interface"
homepage = "https://github.com/garryod/xchemlab_soakdb_interface"
readme = "../README.md"

[dependencies]
axum = { version = "0.6.15", features = ["ws", "headers", "macros"] }
async-graphql = { version = "5.0.10", features = ["uuid", "tracing", "chrono"] }
async-graphql-axum = { version = "5.0.9" }
chrono = { version = "0.4.26", default-features = false }
clap = { version = "4.3.3", features = ["derive", "env"] }
derive_more = { version = "0.99.17" }
dotenvy = { version = "0.15.7" }
itertools = { version = "0.10.5" }
opa_client = { path = "../opa_client", features = ["graphql"] }
soakdb = { path = "../soakdb" }
tokio = { version = "1.28.2", features = ["rt-multi-thread", "macros"] }
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
url = { version = "2.4.0" }
