[package]
name = "backend"
version = "0.1.0"
edition = "2021"
authors = ["Garry O'Donnell <garry.o'donnell@diamond.ac.uk>"]
description = "An XChemLab service, used to export legacy SoakDB sqlite files."
license = "Apache-2.0"
repository = "https://github.com/garryod/xchemlab_soakdb_interface"
homepage = "https://github.com/garryod/xchemlab_soakdb_interface"
readme = "../README.md"

[dependencies]
async-graphql = { version = "5.0.7", features = ["uuid", "tracing"] }
async-graphql-axum = "5.0.7"
axum = { version = "0.6.15", features = ["ws", "headers"] }
clap = { version = "4.3.0", features = ["derive"] }
derive_more = { version = "0.99.17" }
soakdb = { path = "../soakdb", features = ["graphql-models"] }
tokio = { version = "1.28.2", features = ["rt-multi-thread", "macros"] }
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
