federation_version: 2
subgraphs:
  crystal_library:
    routing_url: http://localhost:80
    schema:
      subgraph_url: http://localhost:80
  compound_library:
    routing_url: http://localhost:81
    schema:
      subgraph_url: http://localhost:81
  compound_soaking:
    routing_url: http://localhost:82
    schema:
      subgraph_url: http://localhost:82