apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oauth-provider
  namespace: xchemlab
spec:
  encryptedData:
    client_id: AgCpGpJ5sQQuNAioQheWYL/QrzyrDEnwRsKqygNDUTas3ltZ40z+SMc3zoRCQLLAOmXKV4tsB6o/Dnkf2UPU+ZjExImf+OAc0TyPIYYkIyrTE9iDV2N8thR/nbNWjwhjFUUPrc8zpVfVSD3yfq88UUv8clbJ9Tj9gtCD+WYkszo3eAP0I04xQVWaYvHQcjtsd9szCOc1ryFOlmAc3KmYQj+4vb0nFoiqbeiz5i1TLqlFjsPNT4i6WrkLAmH3CDV0twGGbaf4/dOKJo5SKWafTfMRO4WoKiiHGBKvo+SZsVqO55o1BzfNbL1s0LN9uzh35ed8MupMfM14wW2ajb3VZtxHnFhP4fEPml33Wl3uo4S2T4FGTtF/PX+DBYAPwPGJDATv8TytMOdC177ELlxEA34oi6kyz6ByAIOu10KUzCRdSs+OdjCC9KcoIYL+phpp5O6a6lstjf3ZTH/sHre32QX8wVSCDyBjFjAVUTYoSbRr6S8O6exgXA+e60lEsMhOlVvIMz+amj4GMK/kZ1EjW2JjwOr4VM+4TPnhWEcwyiwVEXVzqfYLzdwfLek0l91+kY+8TL9D327dxpx15jO2p4kzyDhoApozlig3RAVZI3APfktp/wu/vLZhAUoQQvAFcaSTHmcaSQoohWOrLlCRrzKeK7oZ/4RR5H05bpEVEcQk9EFJEjiGxDbkS+NSvrCpZ5dv0VP+DJOb1bfUnv08pJd5AqM=
    client_secret: AgCLElokLHwM7XUTIaKMpxhIXbX28pAwzUaTgwFw6/KmIK+PDijJvvjGRGAOfsAh+5Y1+ndQ7xPL/Mq3UwueL5B5PIuClOY+KQEOfrdIy5oBzsMP31n7ZPlxSxHAeVlLa31mvBAj83yFDYvylCkT1UiAIe2tsrnO50d9tIER7vLfYnN78i077kN2fc5tgkYF4U2rSXFgLIeHKSmxU+Q/0XXQIsv/JeMrFLwoQUXH3hrkP208v3ciKuSoRq6cYMygB5KofW72RnK2ih8tJM4hWbgpU2kcoMSGAPCHWBX0bRD0Kpw2H8AY1lUpiLo21iMjEcQnQunInKpIEHz3ankAyUb+Si535ujxvi14iu8vyADhKLDXmlFjc/OtVstWN0pmghyP0AiT9CwztkWUa9cYtXCbw9JQ36AsN0S9vneRCCZl8ds8Eb1QAJfnfqkka3fWMZ1VYlqwrNpzD8N1q4n8/SeDt/78RXspm6W20Hod1hMlCh+SBEKsWQZF9JIZlJpeUbyXuhNkN03hvo7k5rYPrTbDzDnVnFo/HRcU14jcVW8CSp/lx09YsgpxZImaqxwUCfxs5FTg/FIbiXCU1s2rBlLWaM2KjYn+u0wFpZYdCUqisc70wc3Mtqx2DiZMrqcqYetI4vPrMj2BUu7bU8Oo1P0gyUX1IYj+e53yGwz4m65KolAQ35zlwwXJiiTeXlVklvNcJuqQ7xEGWbsZIbd6ctp8/2M=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: oauth-provider
      namespace: xchemlab
    type: Opaque

