apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: targeting-s3-secret
  namespace: xchemlab
spec:
  encryptedData:
    access-key-id: AgBRB7yfLmpn6rVU2Y3umqGLq+7dY3WyZ9ow1jmQNEpmfxzVVEcdSeftf9BRuwuEiYkmvn5YpCB7nYpCwZvGhIHb6xJfyV4f3so8ui5GZZW9UZDGAcoCeXJ7/acng/LrZ1SliBSzXHB4DJNMK8oJHDkCAHDWVrYAsm8p4insO3LHs4QG6kGat8xkfWdlrpOq4CrY/SYp1zXIn+Jzc7IloLfQS5LQwwkXhskTaLhijHGb+rV+h2rJqGyui0MtvS6h8wa6k/UJOHzRD76fKepoSMHl2QakWOam6XJO2xvwhx3VT981m/45pDqtFDbUMM/znVYnS0h9YHRFu8FDOzw1QEJIgxTmenXp2kDB81+g4WB+fqbg6KgYgP0v5WQKjvAN5mszAqGL361JOwhO2kYR6Y0v/B3HR5doeIb6k9mSwB5q1yuCWegdELqz6LzLaejX5wlUDEzOzbJx4V5tprkG0/vvM3YvFG9CkFamVBARhjg1z4KxhCpu4kgNwkpaOm64v52OpBqjY2S68kgdlbkYO3GQ71Oszk+m5qr8zJadiu+TYObVTEnsKL5hZ+4xUkfLTjkHjNV65akF18FHgRtajgDi19FLU61FbF0olfL7lWsiwjZCfFBO96xaO6e6AQ3DRb2OTRJWCIvMwr134jGgG+9v9KK25jPrPRvXmnRH3Z/fVzNjNzwcf4kOPq1UMmJKq3dnGSIngB8QRSpaeDShXz6Ima07Qchr/Xn/uWjw+Um25vK5GVnKKL9qlBBdIKgXMs5YWMqobN3+HDZisMWLH1FS/df+9C0gSGfYO9ELKdFqBGTcp8Z5Nag0atGF5KDcJ8O5mP1f7muHYxqlC8C4cUrB7U624rctOU6OjirdRPyglw==
    secret-access-key: AgC0QHZNQY2LUmK5LV8uQLyfvazpKRIPdZhcbXIh0U+quwB0ME1D1u7E3n+y0zGpxvdc/4T/AwKfACwKQpzgXNU9G8rKQJi7qi1O6E/qjoQtzj+6RmaULqlgBdU22fAYEYWvwhp4ZNoZGAsgnI3dlWZ9mZuB46mudtixNQNVtPNLXaD2d2Uogg5VuqAeI1trvSPtVz+hyZCsWUFoTlHfMV2XJ4cGMoe67IOd/09S/BGTrwpiapPb1P+K2lVLXU7YDNO9Xec+xVLIuWWylgYGMLRg68JCMmPvA9SEqiYUF9eU78jdHUE4KLUrwZ+fJsoDr0yk7sOY0JS7y+A1+KtTPmF33MbkMtNMIwrtOFsxP8CnBmUW7xp3RBgPk0kkCqnhVv0NCfWRtnVfxQmvi2iYkMapRgDNmUVx8iTtjZgLpzNSNeI7eOOBlny+Ads4CcEMEhfd00mZag+qP9ogrLhoHKW03+1fiPEpz7Z4BwHpssTlkcVIvyzUFXKqG4PC9XA641vVTApUbDawdlhYlDge45DuthJz8WSG+cTpnx1N0rTiW3z1i3Gcy+ppzL9EgWEq8m+wRMId24moHFZFxHZYfbQeVWkOwjdJ/ukix+DlcMSDTGfgtzfBTnbsntpdimbqCAhbCtZs8WXo+hwDHzYpGYvhG0V0F9noOqcVFX3W9jEfmfppf9uWW8yyPL9mOZeSYoUVupwOAynpM7SRqKk4LNRyo537SqmgeZUlrltFMYeoA7rQ9lwpJXW/ehVi9i1I6l/DJG4epk446zDGM41keBJrAIIGNYdJ+x89mykRtZDdbMhLop4BXCjyrq6jAwvFA72+mHpe6oYboNcGC7KGN2Rh2Fl0qNsdLp957++Se8p+Dg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: targeting-s3-secret
      namespace: xchemlab
    type: Opaque

