version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:z
    command: sleep infinity

  opa:
    image: docker.io/openpolicyagent/opa:0.53.1-envoy
    volumes:
      - ../policies:/policies:z
    command:
      - run
      - --server
      - --set=plugins.envoy_ext_authz_grpc.enabled=true
      - --watch
      - /policies

  envoy:
    image: docker.io/envoyproxy/envoy:v1.26.2
    volumes:
      - ./envoy.yaml:/config/envoy.yaml:z
    ports:
      - 8080:80
    environment:
      ENVOY_UID: 0
    command:
      - --config-path /config/envoy.yaml
