apiVersion: v2
name: xchemlab
description: The XChemLab stack
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.1.0"

dependencies:
  - name: chimp-chomp
    version: 0.0.1
    condition: chimp-chomp.enabled
  - name: pin-packing
    version: 0.0.1
    condition: pin-packing.enabled
  - name: grafana
    repository: https://grafana.github.io/helm-charts
    version: 6.58.8
    condition: grafana.enabled
  - name: keda
    repository: https://kedacore.github.io/charts
    version: 2.10.2
    condition: keda.enabled
  - name: opa-kube-mgmt
    repository: https://open-policy-agent.github.io/kube-mgmt/charts
    version: 8.3.0
    condition: opa-kube-mgmt.enabled
  - name: prometheus
    repository: https://prometheus-community.github.io/helm-charts
    version: 23.3.0
    condition: prometheus.enabled
  - name: thanos
    repository: oci://docker.io/bitnamicharts
    version: 12.11.0
    condition: thanos.enabled
  - name: rabbitmq
    repository: oci://docker.io/bitnamicharts
    version: 12.0.7
    condition: rabbitmq.enabled
  - alias: oauth2-proxy-thanos
    name: oauth2-proxy
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 3.7.4
    condition: oauth2-proxy-thanos.enabled
  - alias: oauth2-proxy-alertmanager
    name: oauth2-proxy
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 3.7.4
    condition: oauth2-proxy-alertmanager.enabled
