replicaCount: 1

nameOverride: ""
fullnameOverride: ""

rabbitmq:
  enabled: true
  service:
    type: LoadBalancer
    # Exposed as rmq.xchemlab.diamond.ac.uk
    loadBalancerIP: 172.23.169.229

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
