replicaCount: 1

nameOverride: ""
fullnameOverride: ""

rabbitmq:
  enabled: true
  persistence:
    enabled: false
  serviceBindings:
    enabled: true

chimp-chomp:
  enabled: true
  queue:
    host:
      secretNameSuffix: rabbitmq-svcbind
      secretKey: uri
  volumes:
    - name: labxchem
      hostPath:
        path: /dls/labxchem
        type: Directory
  containerVolumeMounts:
    - name: labxchem
      mountPath: /dls/labxchem
      mountPropagation: HostToContainer

keda:
  enabled: false

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
