replicaCount: 1

nameOverride: ""
fullnameOverride: ""

chimp-chomp:
  enabled: true
  queue:
    host:
      secretNameSuffix: rabbitmq-svcbind
      secretKey: uri
  volumes:
    - name: labxchem
      hostPath:
        path: /dls/labxchem
        type: Directory
  containerVolumeMounts:
    - name: labxchem
      mountPath: /dls/labxchem
      mountPropagation: HostToContainer

pin-packing:
  enabled: true
  database:
    host: postgres://postgresql-ha-pgpool
    user: postgres
    password:
      secretName: postgres-passwords
      secretKey: password
  opa:
    serviceSuffix: opa-kube-mgmt

keda:
  enabled: false

opa-kube-mgmt:
  enabled: true
  mgmt:
    enabled: false
  serviceAccount:
    create: false
  rbac:
    create: false

prometheus:
  enabled: true

  kube-state-metrics:
    enabled: false

  prometheus-node-exporter:
    enabled: false

  prometheus-pushgateway:
    enabled: false

  rbac:
    create: false

  alertmanager:
    serviceAccount:
      create: false
      name: default-full-access-mounted
    ingress:
      enabled: true
      hosts:
        - host: xchemlab-alertmanager.diamond.ac.uk
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - xchemlab-alertmanager.diamond.ac.uk
    extraArgs:
      web.external-url: https://xchemlab-alertmanager.diamond.ac.uk
    configmapReload:
      enabled: true

  server:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - prometheus
            topologyKey: kubernetes.io/hostname
    persistentVolume:
      enabled: false
    retention: 7d
    statefulSet:
      enabled: true
    alertmanagers:
      - kubernetes_sd_configs:
          - role: pod
            namespaces:
              own_namespace: true
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            regex: <namespace>
            action: keep
          - source_labels:
              [__meta_kubernetes_pod_label_app_kubernetes_io_instance]
            regex: <release-name>
            action: keep
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            regex: alertmanager
            action: keep
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            regex: "9093"
            action: keep

  serviceAccounts:
    prometheus-node-exporter:
      create: false
      name: default-full-access-mounted
    pushgateway:
      create: false
      name: default-full-access-mounted
    server:
      create: false
      name: default-full-access-mounted

  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: prometheus
          static_configs:
            - targets:
                - localhost:9090
        - job_name: "kubernetes-service-endpoints"
          kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                own_namespace: true
          relabel_configs:
            - source_labels:
                [__meta_kubernetes_service_annotation_prometheus_io_scrape]
              action: keep
              regex: true
            - source_labels:
                [__meta_kubernetes_service_annotation_prometheus_io_scheme]
              action: replace
              target_label: __scheme__
              regex: (https?)
            - source_labels:
                [__meta_kubernetes_service_annotation_prometheus_io_path]
              action: replace
              target_label: __metrics_path__
              regex: (.+)
            - source_labels:
                [
                  __address__,
                  __meta_kubernetes_service_annotation_prometheus_io_port,
                ]
              action: replace
              target_label: __address__
              regex: (.+?)(?::\d+)?;(\d+)
              replacement: $1:$2
            - action: labelmap
              regex: __meta_kubernetes_service_annotation_prometheus_io_param_(.+)
              replacement: __param_$1
            - action: labelmap
              regex: __meta_kubernetes_service_label_(.+)
            - source_labels: [__meta_kubernetes_namespace]
              action: replace
              target_label: namespace
            - source_labels: [__meta_kubernetes_service_name]
              action: replace
              target_label: service
            - source_labels: [__meta_kubernetes_pod_node_name]
              action: replace
              target_label: node
        - job_name: "kubernetes-pods"
          kubernetes_sd_configs:
            - role: pod
              namespaces:
                own_namespace: true
          relabel_configs:
            - source_labels:
                [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
              action: keep
              regex: true
            - source_labels:
                [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
              action: keep
              regex: true
            - source_labels:
                [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
              action: replace
              regex: (https?)
              target_label: __scheme__
            - source_labels:
                [__meta_kubernetes_pod_annotation_prometheus_io_path]
              action: replace
              target_label: __metrics_path__
              regex: (.+)
            - source_labels:
                [
                  __address__,
                  __meta_kubernetes_pod_annotation_prometheus_io_port,
                ]
              action: replace
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $1:$2
              target_label: __address__
            - action: labelmap
              regex: __meta_kubernetes_pod_annotation_prometheus_io_param_(.+)
              replacement: __param_$1
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - source_labels: [__meta_kubernetes_namespace]
              action: replace
              target_label: namespace
            - source_labels: [__meta_kubernetes_pod_name]
              action: replace
              target_label: pod
            - source_labels: [__meta_kubernetes_pod_phase]
              regex: Pending|Succeeded|Failed|Completed
              action: drop

rabbitmq:
  enabled: true
  persistence:
    enabled: false
  serviceBindings:
    enabled: true

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
