replicaCount: 1

nameOverride: ""
fullnameOverride: ""

rabbitmq:
  enabled: true
  persistence:
    enabled: false
  serviceBindings:
    enabled: true

keda:
  enabled: false

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
