nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/diamondlightsource/xchemlab-chimp-chomp
  pullPolicy: Always
  tag: ""

imagePullSecrets: []

queue:
  host:
    secretNameSuffix: ""
    secretKey: ""
  channel: ""

autoscaling:
  jobsPerReplica: 30
  minReplicas: 0
  maxReplicas: 10

serviceAccount:
  create: false
  name: ""

podAnnotations: {}

podSecurityContext: {}

volumes: []

containerVolumeMounts: []

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
