nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/diamondlightsource/xchemlab-pin-packing
  pullPolicy: Always
  tag: ""

imagePullSecrets: []

database:
  host: ""
  user: ""
  password:
    secretName: ""
    secretKey: ""

opa:
  serviceSuffix: ""

replicaCount: 1

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: false
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
